version: "3"
services:
  nest-bp:
    container_name: nest-bp
    restart: always
    build: .
    image: nest-bp
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://postgres:postgres@nest-bp_pgsql:5432/nest-bp
  postgres:
    # 18.3
    image: postgres@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    container_name: nest-bp_pgsql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest-bp
    volumes:
      - nest-bp-data:/var/lib/postgresql
volumes:
  nest-bp-data:
