version: "3"
services:
  nest-bp:
    container_name: nest-bp
    restart: always
    build: .
    image: nest-bp
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://postgres:postgres@nest-bp_pgsql:5432/nest-bp
  postgres:
    image: postgres:15
    container_name: nest-bp_pgsql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest-bp
    volumes:
      - nest-bp-data:/var/lib/postgresql/data
volumes:
  nest-bp-data:
