version: "3"
services:
  nest-boilerplate:
    container_name: nest-boilerplate
    restart: always
    build: .
    image: nest-boilerplate
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://postgres:postgres@nest-boilerplate_pgsql:5432/nest-boilerplate
  postgres:
    image: postgres:11.2
    container_name: nest-boilerplate_pgsql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest-boilerplate
    volumes:
      - nest-boilerplate-data:/var/lib/postgresql/data
volumes:
  nest-boilerplate-data:
