services:
  nest-bp:
    container_name: nest-bp
    restart: unless-stopped
    build: .
    image: nest-bp
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://postgres:postgres@nest-bp_pgsql:5432/nest-bp
      - REDIS_URL=redis://nest-bp_redis:6379
  postgres:
    # postgres:18.0-alpine3.22
    image: postgres@sha256:48c8ad3a7284b82be4482a52076d47d879fd6fb084a1cbfccbd551f9331b0e40
    container_name: nest-bp_pgsql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest-bp
    volumes:
      - nest-bp-data:/var/lib/postgresql
  redis:
    # redis:8.8.0-alpine3.23
    image: redis@sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005
    container_name: nest-bp_redis
    restart: unless-stopped
volumes:
  nest-bp-data:
