version: "3"
services:
  grafana:
    image: grafana/grafana:11.0.0
    container_name: nb-grafana
    user: "0"
    ports:
      - "9000:3000"
    environment:
      - GF_PATHS_CONFIG=/conf/grafana-custom.ini
    volumes:
      - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./config/grafana.ini:/conf/grafana-custom.ini
      - nb_grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: nb-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - nb_prometheus:/prometheus
    command:
      [
        "--log.level=debug",
        "--config.file=/etc/prometheus/prometheus.yml",
        "--enable-feature=remote-write-receiver",
        "--query.lookback-delta=30s",
        "--enable-feature=otlp-write-receiver"
      ]
  tempo:
    image: grafana/tempo:2.4.1
    container_name: nb-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - nb_tempo:/var/tempo
  loki:
    image: grafana/loki:3.0.0
    container_name: nb-loki
    user: "0"
    ports:
      - "9100:3100"
    command: -config.file=/etc/loki-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki-config.yaml
      - nb_loki:/etc/loki
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    container_name: nb-otel-collector
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317" # GRPC
      - "4318:4318" # HTTP
      - "8889:8889" # App metrics
      - "55679:55679" # zpages
volumes:
  nb_grafana:
  nb_prometheus:
  nb_tempo:
  nb_loki: