receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
#  prometheus:
#    endpoint: 0.0.0.0:8889
#    namespace: nb
#    send_timestamps: true
  prometheusremotewrite:
    # help and type are missing: https://github.com/prometheus/prometheus/issues/13163
    endpoint: http://prometheus:9090/api/v1/write
    namespace: nb
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  debug:
#    verbosity: detailed

extensions:
  zpages:
    # See https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension/README.md
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
